### ISSUE TITLE
Bug when dictating in non-English and wanting to keep it like that

### ISSUE THREAD

**Issue by dekked** [sphantix/whisper.cpp.python#1]
The following snippet forces Whisper to output English even when I want it to output Spanish:

```python
# print some info about the processing
if whisper_cpp.whisper_is_multilingual(self.whisper_ctx):
    if language != "en" or translate:
        language = "en"
        translate = False
        print(f"{__name__}: WARNING: multilingual model detected, disabling translation and setting language to english")
```

Moreover, it only runs if verbose flag it set to True (this is a bug). If I want to dictate in Spanish and keep it like that, I need to disable verbose.

If verbose is enabled, whisper will unfortunately output English :(

I would maybe suggest removing this snippet altogether?

**Comment by sphantix** [comment]
@dekked  Sorry I just saw this issue, I've fixed it in the latest code , sincerely hope it's not too late [fix](https://github.com/sphantix/whisper-cpp-pybind/commit/e9437f499ed0de075f3fc84475224a64fa2fad89)

**Comment by dekked** [comment]
It's never too late ;)
